services:
  gitlab-runner:
    volumes:
      - gitlab-runner-volume:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: ${CONTAINER_NAME}
    network_mode: "host"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

  gitlab-runner-setup:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: "no"
    network_mode: "host"
    image: ubuntu:latest
    depends_on:
      - gitlab-runner
    entrypoint: ["bash","-c","/usr/bin/docker exec ${CONTAINER_NAME} gitlab-runner register --non-interactive --url '${GITLAB_URL}' --token \"$TOKEN\" --executor \"${EXECUTOR}\" ${EXTRA}"]

volumes:
  gitlab-runner-volume:
